INSERT INTO product (name, category, price, image_url) VALUES
('Mobile', 'Electronics', 500, 'mobile.png'),
('Laptop', 'Electronics', 1200, 'laptop.png'),
('Camera', 'Electronics', 900, 'camera.jpeg'),
('OLED TV', 'Electronics', 4500, 'oled-tv.jpg'),
('Mouse', 'Electronics', 100, 'mouse.png'),
('Keyboard', 'Electronics', 150, 'keyboard.jpg'),
('Headphones', 'Electronics', 250, 'headphones.png'),
('Tablet', 'Electronics', 800, 'tablet.png'),
('Speaker', 'Electronics', 300, 'speaker.png'),
('Smart Watch', 'Electronics', 600, 'smartwatch.png'),
('Football', 'Sports', 120, 'football.png'),
('Basketball', 'Sports', 150, 'basketball.png'),
('Tennis Racket', 'Sports', 450, 'tennis-racket.png'),
('Tennis Balls (3-pack)', 'Sports', 80, 'tennis-balls.png'),
('Boxing Gloves', 'Sports', 500, 'boxing-gloves.png'),
('Yoga Mat', 'Sports', 200, 'yoga-mat.png'),
('Dumbbells (2x5kg)', 'Sports', 350, 'dumbbells.png'),
('Treadmill', 'Sports', 6500, 'treadmill.png'),
('Bicycle Helmet', 'Sports', 300, 'bicycle-helmet.png'),
('Water Bottle', 'Sports', 60, 'water-bottle.png'),
('Jeans', 'Clothing', 600, 'jeans.png'),
('Hoodie', 'Clothing', 500, 'hoodie.png'),
('Jacket', 'Clothing', 900, 'jacket.png');